baseurl = "https://www.troop105treedrive.com"
languageCode = "en"
title = "2023 Chistmas Tree Drive"
theme = "soho"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5
ignoreErrors = ["error-remote-getjson"]

[params]
title = "2024 Christmas Tree Drive"
description = "Pembroke Troop 105"
# gravatar = "soho@example.com"
images = ["profile-tree.png"]
profilePicture = "tree-drive-square.png"
copyright = "Pembroke Troop 105"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
builtWith = true
mainSections = ["post"]

## Set custom theme color.
# themeColor = "#fc2803"




[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
      unsafe = true
