#!/usr/bin/env bash
set -e
cd ${HOME}/tree105

echo "git pull"
git pull

echo "caddy reformat and reload"
docker compose exec --workdir /etc/caddy caddy caddy fmt --overwrite
docker compose exec --workdir /etc/caddy caddy caddy reload

echo "docker down"
docker compose down server

echo "docker build"
docker compose build

echo "docker compose up"
docker compose up -d

echo "docker compose logs follow"
docker compose logs -f
